name: Build and release Systemd sysext images
on:
  schedule:
    # Times are in UTC, this job is run daily @ 14HRS = 9AM EST, 20HRS = 3PM EST
    - cron: "0 14,20 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v3
      # build the images and generate a manifest
      - name: build
        run: |
          set -euxo pipefail

          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            gawk

            pwd
            ls -la

          APPS=( $( find . -maxdepth 1 -name "create*.sh" -exec basename {} \; ) )
          images=()

          for app in "${APPS[@]}"; do
              eval _version=\$\( "$( awk '/#_VERSION/ {print substr($0, index($0,$2))}' ./${app} )" \)
              images+=("${app}-${_version}")
          done

          streams=()

          for image in "${images[@]}"; do
              component="${image%-*}"
              version="${image#*-}"
              for arch in x86-64 arm64; do
                ARCH="${arch}" "./${component}" "${version}" "${component}"
                mv "${component}.raw" "${image}-${arch}.raw"
              done
              streams+=("${component}:-@v")
          done
          for stream in "${streams[@]}"; do
              component="${stream%:*}"
              pattern="${stream#*:}"
              cat << EOF > "${component}.conf"
           [Transfer]
           Verify=false
           [Source]
           Type=url-file
           Path=https://github.com/forwardcomputers/sysext/releases/latest/download/
           MatchPattern=${component}${pattern}-%a.raw
           [Target]
           InstancesMax=3
           Type=regular-file
           Path=/opt/extensions/${component%-*}
           CurrentSymlink=/etc/extensions/${component%-*}.raw
          EOF
          done

          cat << EOF > "noop.conf"
          [Source]
          Type=regular-file
          Path=/
          MatchPattern=invalid@v.raw
          [Target]
          Type=regular-file
          Path=/
          EOF

          # Fetch the current SHA256SUMS to append to it the new list of sha256 sums.
          curl -fsSLO https://github.com/forwardcomputers/sysext/releases/download/latest/SHA256SUMS
          sha256sum *.raw >> SHA256SUMS
          sort --unique --key 2 --output SHA256SUMS SHA256SUMS

      # create a Github release with the generated artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SHA256SUMS
            *.raw
            *.conf
