name: Build and release Systemd sysext images
on:
  schedule:
    # Times are in UTC, this job is run daily @ 14HRS = 9AM EST, 20HRS = 3PM EST
    - cron: "0 14,20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v4
      # build the images and generate a manifest
      - name: build
        run: |
          set -x
          echo "_update=false" >> $env:GITHUB_ENV

          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            gawk

          curl -fsSLO --output-dir /tmp $( curl -sL 'https://api.github.com/repos/forwardcomputers/sysext/releases/latest' | jq -r '.assets[] | select( .name=="SHA256SUMS" ).browser_download_url' )

          APPS=( $( find . -maxdepth 1 -name "create*.sh" -exec bash -c 'echo ${0:9:-10}' {} \; ) )
          images=()

          for app in "${APPS[@]}"; do
              eval _version=\$\( "$( awk '/#_VERSION/ {print substr($0, index($0,$2))}' ./create_${app}_sysext.sh )" \)
              image="${app}-${_version}"
              grep "${image}" /tmp/SHA256SUMS || images+=("${app}-${_version}")
          done

          streams=()

          for image in "${images[@]}"; do
              component="${image%-*}"
              version="${image#*-}"
              for arch in x86-64 arm64; do
                ARCH="${arch}" "./create_${component}_sysext.sh" "${version}" "${component}"
                mv "${component}.raw" "${image}-${arch}.raw"
              done
              streams+=("${component}:-@v")
          done
          if (( ${#streams[@]} )); then
            for stream in "${streams[@]}"; do
                component="${stream%:*}"
                pattern="${stream#*:}"
                cat << EOF > "${component}.conf"
            [Transfer]
            Verify=false
            [Source]
            Type=url-file
            Path=https://github.com/forwardcomputers/sysext/releases/latest/download/
            MatchPattern=${component}${pattern}-%a.raw
            [Target]
            InstancesMax=3
            Type=regular-file
            Path=/opt/extensions/${component%-*}
            CurrentSymlink=/etc/extensions/${component%-*}.raw
            EOF
            done

            cat << EOF > "noop.conf"
            [Source]
            Type=regular-file
            Path=/
            MatchPattern=invalid@v.raw
            [Target]
            Type=regular-file
            Path=/
            EOF

            # Fetch the current SHA256SUMS to append to it the new list of sha256 sums.
            curl -fsSLO https://github.com/forwardcomputers/sysext/releases/download/latest/SHA256SUMS || true
            sha256sum *.raw >> SHA256SUMS
            sort --unique --key 2 --output SHA256SUMS SHA256SUMS

            echo "_update=true" >> $env:GITHUB_ENV
          fi

      # create a Github release with the generated artifacts
      - name: Generate release tag
        if: env._update == 'true'
        id: tag
        run: |
          echo "::set-output name=release_tag::Built_$(date +"%Y.%m.%d_%H-%M")"
      - name: release
        if: env._update == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            SHA256SUMS
            *.raw
            *.conf
